controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: True
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
trajectory_controller:
  ros__parameters:
    use_sim_time: True
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    interpolation_method: splines